---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _industry_page
  label: Industry pages
  create: all
  match: "**/*"
  templates:
  - industry-page
- type: directory
  path: _case_studies
  label: Case studies
  create: all
  match: "**/*"
  templates:
  - case-study
- type: directory
  path: _feature_page
  label: Feature Page
  create: all
  match: "**/*"
  templates:
  - feature_page
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
